### ISSUE TITLE
500 error after uploading the json file

### ISSUE THREAD

**Issue by saleh-mir** [nicolay-zlobin/jesse-trades-info#5]
After uploading my json backtest file, I get a 500 error in the browser. I checked the log in the running Nuxt server in my terminal and here is what I got:

```
 ERROR  Request failed with status code 500                                                                                                                                            13:20:17

  at createError (node_modules/axios/lib/core/createError.js:16:15)
  at settle (node_modules/axios/lib/core/settle.js:17:12)
  at Unzip.handleStreamEnd (node_modules/axios/lib/adapters/http.js:236:11)
  at Unzip.emit (events.js:314:20)
  at Unzip.EventEmitter.emit (domain.js:486:12)
  at endReadableNT (_stream_readable.js:1252:12)
  at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

When I revisit the http://localhost:3000 address, I see the file in the "Uploaded backtests", when I click on it, same error happens.

**Comment by nicolay-zlobin** [comment]
Can you provide an example of a JSON file with which the error occurs?

**Comment by saleh-mir** [comment]
sorry man. Forgot to copy `.env` file and enter my database info

**Comment by nicolay-zlobin** [comment]
It's ok. Feel free to contact me if you have any further questions.
